language: java
sudo: false
dist: trusty
jdk:
  - oraclejdk8
install: true
script:
  - mvn org.jacoco:jacoco-maven-plugin:prepare-agent verify sonar:sonar -B -e -V
notifications:
  email: false
addons:
  sonarcloud:
    organization: "spotbugs"
    branches:
      - master
      - stabilize-build
    token:
      secure: "LzizJSH1+fj2w752WgdurWoQkaPSCB9uSioWr26hvcW1F0EGXhLqeeRPOI+2Nwg8YpSni59jyIGWBt6uFtwzLSD0mtyWjsXWx1Q6PlmV99HV2eTYjG74ir9qWvZTDzmVBiU0tOXEDEeTIqs4MDVNuWXzMARFQRLHbcq+U3tSCj8="
    github_token:
      secure: "CTSQvp5VkT63mf93ngenRkxzUtaqGSktI5T1N9fUfcawxSE8BjrOPA90u5hBJUNVC+Jq8my4mMWs0MGb30SQgNJ5Cyc6zaqmyl6E/de5fGbOjvGkFmH8ZMtfApLfjx8X93OPzZkZW9LZYCsxsBROM9c/vT08/MVjFJkCGrCHXg0="
